seed: 42
artifacts_dir: models/artifacts

models:
  isolation_forest:
    n_estimators: 200
    contamination: 0.02
    random_state: 42
  random_forest:
    n_estimators: 200
    max_depth: 12
    class_weight: balanced
    random_state: 42
  xgboost:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.9
    colsample_bytree: 0.9
    random_state: 42
